
export const estados = [
    {nome: "Acre", UF: "AC"},
    {nome: "Alagoas", UF: "AL"},
    {nome: "Amapá", UF: "AP"},
    {nome: "Amazonas", UF: "AM"},
    {nome: "Bahia", UF: "BA"},
    {nome: "Ceará", UF: "CE"},
    {nome: "Destrito Federal", UF: "DF"},
    {nome: "Espírito Santo", UF: "ES"},
    {nome: "Goiás", UF: "GO"},
    {nome: "Maranhão", UF: "MA"},
    {nome: "Mato Grosso do Sul", UF: "MS"},
    {nome: "Minas Gerais", UF: "MG"},
    {nome: "Pará", UF: "PA"},
    {nome: "Paraíba", UF: "PB"},
    {nome: "Paraná", UF: "PR"},
    {nome: "Pernambuco", UF: "PE"},
    {nome: "Piauí", UF: "PI"},
    {nome: "Rio de Janeiro", UF: "RJ"},
    {nome: "Rio Grande do Norte ", UF: "RN"},
    {nome: "Rio Grande do Sul", UF: "RS"},
    {nome: "Rondônia", UF: "RO"},
    {nome: "Roraima", UF: "RR"},
    {nome: "Santa Catarina", UF: "SC"},
    {nome: "São Paulo", UF: "SP"},
    {nome: "Sergipe", UF: "SE"},
    {nome: "Tocantins", UF: "TO"},
] 